p8105_hw2_khs2318
================
Kayla Schiffer-Kane
2023-10-04

- [Problem 1](#problem-1)
  - [Clean pols_month](#clean-pols_month)
  - [Clean snp](#clean-snp)
  - [Clean Unemployment](#clean-unemployment)
  - [Merge all data](#merge-all-data)

``` r
library(tidyverse)
```

# Problem 1

Dataset is FiveThirtyEight data

## Clean pols_month

Clean the data in pols-month.csv. Use `separate()` to break up the
variable mon into integer variables `year`, `month`, and `day`; replace
`month` number with month name; create a `president` variable taking
values `gop` and `dem`, and remove `prez_dem` and `prez_gop`; and remove
the `day` variable.

``` r
pols_month =
  read_csv('./data/fivethirtyeight_datasets/pols-month.csv') |>
  separate(mon, c("year","month","day")) |>
  mutate(month = month.name[as.numeric(month)]) |>
  mutate(president = recode(prez_dem, "1" = "dem", "0" = "gop")) |>
  select(-prez_dem,-prez_gop, - day)
  
head(pols_month)
```

    ## # A tibble: 6 × 9
    ##   year  month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##   <chr> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ## 1 1947  January       23      51     253      23      45     198 dem      
    ## 2 1947  February      23      51     253      23      45     198 dem      
    ## 3 1947  March         23      51     253      23      45     198 dem      
    ## 4 1947  April         23      51     253      23      45     198 dem      
    ## 5 1947  May           23      51     253      23      45     198 dem      
    ## 6 1947  June          23      51     253      23      45     198 dem

## Clean snp

Second, clean the data in snp.csv using a similar process to the above.
For consistency across datasets, arrange according to year and month,
and organize so that year and month are the leading columns.

``` r
snp =
  read_csv('./data/fivethirtyeight_datasets/snp.csv') |>
  separate(date, c("month","day","year"), sep = '/') |>
  mutate(month = month.name[as.numeric(month)]) |>
  mutate(year = if_else(year > 15, paste0("19",year), paste0("20",year))) |> 
  #arrange(year, month) |>
  select(year,month,close)
tail(snp)
```

    ## # A tibble: 6 × 3
    ##   year  month    close
    ##   <chr> <chr>    <dbl>
    ## 1 1950  June      17.7
    ## 2 1950  May       18.8
    ## 3 1950  April     18.0
    ## 4 1950  March     17.3
    ## 5 1950  February  17.2
    ## 6 1950  January   17.0

## Clean Unemployment

Third, tidy the unemployment data so that it can be merged with the
previous datasets. This process will involve switching from “wide” to
“long” format; ensuring that key variables have the same name; and
ensuring that key variables take the same values.

``` r
unemployment =
  read_csv('./data/fivethirtyeight_datasets/unemployment.csv') |> 
  pivot_longer(Jan:Dec,
               names_to = "month",
               values_to = "percentage") |>
  janitor::clean_names() |>
  mutate(month = month.name[match(month, month.abb)]) |> # Jan -> January 
  mutate(year = as.character(year))
unemployment
```

    ## # A tibble: 816 × 3
    ##    year  month     percentage
    ##    <chr> <chr>          <dbl>
    ##  1 1948  January          3.4
    ##  2 1948  February         3.8
    ##  3 1948  March            4  
    ##  4 1948  April            3.9
    ##  5 1948  May              3.5
    ##  6 1948  June             3.6
    ##  7 1948  July             3.6
    ##  8 1948  August           3.9
    ##  9 1948  September        3.8
    ## 10 1948  October          3.7
    ## # ℹ 806 more rows

## Merge all data

Required casting year in unemployment to character

``` r
data = 
  left_join(pols_month, snp) |>
  left_join(x = _, y = unemployment)

str(data)
```

    ## tibble [822 × 11] (S3: tbl_df/tbl/data.frame)
    ##  $ year      : chr [1:822] "1947" "1947" "1947" "1947" ...
    ##  $ month     : chr [1:822] "January" "February" "March" "April" ...
    ##  $ gov_gop   : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop   : num [1:822] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop   : num [1:822] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem   : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem   : num [1:822] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem   : num [1:822] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president : chr [1:822] "dem" "dem" "dem" "dem" ...
    ##  $ close     : num [1:822] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ percentage: num [1:822] NA NA NA NA NA NA NA NA NA NA ...

``` r
skimr::skim(data)
```

|                                                  |      |
|:-------------------------------------------------|:-----|
| Name                                             | data |
| Number of rows                                   | 822  |
| Number of columns                                | 11   |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |      |
| Column type frequency:                           |      |
| character                                        | 3    |
| numeric                                          | 8    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |      |
| Group variables                                  | None |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| year          |         0 |             1 |   4 |   4 |     0 |       69 |          0 |
| month         |         0 |             1 |   3 |   9 |     0 |       12 |          0 |
| president     |         0 |             1 |   3 |   3 |     0 |        2 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate |   mean |     sd |     p0 |    p25 |    p50 |    p75 |    p100 | hist  |
|:--------------|----------:|--------------:|-------:|-------:|-------:|-------:|-------:|-------:|--------:|:------|
| gov_gop       |         0 |          1.00 |  22.48 |   5.68 |  12.00 |  18.00 |  22.00 |  28.00 |   34.00 | ▆▆▇▅▅ |
| sen_gop       |         0 |          1.00 |  46.10 |   6.38 |  32.00 |  42.00 |  46.00 |  51.00 |   56.00 | ▃▃▇▇▇ |
| rep_gop       |         0 |          1.00 | 194.92 |  29.24 | 141.00 | 176.00 | 195.00 | 222.00 |  253.00 | ▃▇▆▃▅ |
| gov_dem       |         0 |          1.00 |  27.20 |   5.94 |  17.00 |  22.00 |  28.00 |  32.00 |   41.00 | ▆▅▇▆▂ |
| sen_dem       |         0 |          1.00 |  54.41 |   7.37 |  44.00 |  48.00 |  53.00 |  58.00 |   71.00 | ▇▆▇▃▂ |
| rep_dem       |         0 |          1.00 | 244.97 |  31.37 | 188.00 | 211.00 | 250.00 | 268.00 |  301.00 | ▇▂▇▇▅ |
| close         |        36 |          0.96 | 472.85 | 543.29 |  17.05 |  83.67 | 137.26 | 932.06 | 2107.39 | ▇▁▂▁▁ |
| percentage    |        12 |          0.99 |   5.83 |   1.65 |   2.50 |   4.70 |   5.60 |   6.90 |   10.80 | ▃▇▅▂▁ |

The resulting dataset has 822 rows and 11 columns.

- Pols_month has 822 rows, and we created `president` which tells us if
  the president was a gop/dem in a given year. This column was created
  from a combination of `prez_gop` and `prez_dem`, which I tested to
  make sure are truly mutually exclusive. Years include 1947 to 2015
- SNP has 787, with data from 1950 to 2015. Average close price for
  these years is 474.8887404
- Unemployment has unemployment rates from 1948 to 2015. Average
  unemployment for these years is 5.83
- Because the years don’t overlap exactly, we’ll miss some data for
  certain years - hence the “NAs” in the merged dataset - 36 values are
  missing SNP close price `close`, and 12 are missing unemployment rates
  `percentage`.
